// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/BartekTao/nycu-meeting-room-api/internal/domain"
)

type Mutation struct {
}

type PageInfo struct {
	StartCursor *string `json:"startCursor,omitempty"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RoomConnection struct {
	Edges    []*RoomEdge `json:"edges,omitempty"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type RoomEdge struct {
	Node   *domain.Room `json:"node,omitempty"`
	Cursor string       `json:"cursor"`
}

type RoomScheduleConnection struct {
	Edges    []*RoomScheduleEdge `json:"edges,omitempty"`
	PageInfo *PageInfo           `json:"pageInfo"`
}

type RoomScheduleEdge struct {
	Node   *domain.RoomSchedule `json:"node,omitempty"`
	Cursor string               `json:"cursor"`
}

type UpsertRoomInput struct {
	ID         *string            `json:"id,omitempty"`
	Name       string             `json:"name"`
	Capacity   int                `json:"capacity"`
	Equipments []domain.Equipment `json:"equipments,omitempty"`
	Rules      []domain.Rule      `json:"rules,omitempty"`
}

type UserConnection struct {
	Edges    []*UserEdge `json:"edges,omitempty"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type UserEdge struct {
	Node   *domain.User `json:"node,omitempty"`
	Cursor string       `json:"cursor"`
}

type UserEvent struct {
	User   *domain.User   `json:"user"`
	Events []domain.Event `json:"events,omitempty"`
}
