// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/BartekTao/nycu-meeting-room-api/internal/domain"
)

type Booking struct {
	StartAt  int          `json:"startAt"`
	EndAt    int          `json:"endAt"`
	BookedBy *domain.User `json:"bookedBy"`
}

type Mutation struct {
}

type PageInfo struct {
	StartCursor *string `json:"startCursor,omitempty"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RoomConnection struct {
	Edges    []*RoomEdge `json:"edges,omitempty"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type RoomEdge struct {
	Node   *domain.Room `json:"node,omitempty"`
	Cursor string       `json:"cursor"`
}

type UpsertEventInput struct {
	ID              *string  `json:"id,omitempty"`
	Title           string   `json:"title"`
	Description     *string  `json:"description,omitempty"`
	StartAt         int64    `json:"startAt"`
	EndAt           int64    `json:"endAt"`
	RoomID          *string  `json:"roomId,omitempty"`
	ParticipantsIDs []string `json:"participantsIDs,omitempty"`
	Notes           *string  `json:"notes,omitempty"`
	RemindAt        int64    `json:"remindAt"`
}

type UpsertRoomInput struct {
	ID        *string  `json:"id,omitempty"`
	RoomID    string   `json:"roomId"`
	Capacity  int      `json:"capacity"`
	Equipment []string `json:"equipment,omitempty"`
	Rules     []string `json:"rules,omitempty"`
}

type UserConnection struct {
	Edges    []*UserEdge `json:"edges,omitempty"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type UserEdge struct {
	Node   *domain.User `json:"node,omitempty"`
	Cursor string       `json:"cursor"`
}

type UserEvent struct {
	User   *domain.User   `json:"user"`
	Events []domain.Event `json:"events,omitempty"`
}
