apiVersion: apps/v1
kind: Deployment
metadata:
  name: meeting-center-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meeting-center-api
  template:
    metadata:
      labels:
        app: meeting-center-api
    spec:
      containers:
        - name: meeting-center-api
          image: ghcr.io/jammy0611/meetingcenter-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: MONGO_URI
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: GOOGLE_OAUTH_CLIENT_ID
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: GOOGLE_OAUTH_CLIENT_SECRET
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_KEY
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_EXPORTER_OTLP_INSECURE
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: OTEL_EXPORTER_OTLP_INSECURE
            - name: OTEL_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: OTEL_SERVICE_NAME
            - name: REDIS_URI 
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: REDIS_URI
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SENDER_EMAIL
            - name: SENDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: SENDER_PASSWORD
            - name: type
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: type
            - name: project_id
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: project_id
            - name: private_key_id
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: private_key_id
            - name: private_key
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: private_key
            - name: client_email
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: client_email
            - name: client_id
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: client_id
            - name: auth_uri
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: auth_uri
            - name: token_uri
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: token_uri
            - name: auth_provider_x509_cert_url
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: auth_provider_x509_cert_url
            - name: client_x509_cert_url
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: client_x509_cert_url
            - name: universe_domain
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: universe_domain
            - name: GCS_CREDENTIALS_JSON
              value: /etc/gcp/nycu-cncf-9ba3d1230fc5.json
          volumeMounts:
            - name: gcp-credentials
              mountPath: /etc/gcp
              readOnly: true
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials-secret
          # livenessProbe:
          #   httpGet:
          #     path: /ping
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: meeting-center-api
spec:
  type: ClusterIP
  selector:
    app: meeting-center-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080