apiVersion: batch/v1
kind: CronJob
metadata:
  name: reminder-cronjob
  namespace: default
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reminder
            image: ghcr.io/jammy0611/meetingcenter-cronjob:reminder
            imagePullPolicy: IfNotPresent
            command: ["./app"]
          restartPolicy: OnFailure