apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meeting-center-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vue-frontend
                port:
                  number: 80
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: meeting-center-api
                port:
                  number: 8080
          - path: /auth/google/login
            pathType: Prefix
            backend:
              service:
                name: meeting-center-api
                port:
                  number: 8080
          - path: /auth/google/callback
            pathType: Prefix
            backend:
              service:
                name: meeting-center-api
                port:
                  number: 8080
