// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateRoomInput struct {
	ID        *string  `json:"id,omitempty"`
	RoomID    string   `json:"roomId"`
	Capacity  int      `json:"capacity"`
	Equipment []string `json:"equipment,omitempty"`
	Rules     []string `json:"rules,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Room struct {
	ID        string   `json:"id"`
	RoomID    string   `json:"roomId"`
	Capacity  int      `json:"capacity"`
	Equipment []string `json:"equipment,omitempty"`
	Rules     []string `json:"rules,omitempty"`
}

type UpdateEventInput struct {
	Title           *string  `json:"title,omitempty"`
	Description     *string  `json:"description,omitempty"`
	StartTime       *int     `json:"startTime,omitempty"`
	EndTime         *int     `json:"endTime,omitempty"`
	ParticipantsIDs []string `json:"participantsIDs,omitempty"`
	Notes           *string  `json:"notes,omitempty"`
}
