// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateMeetingInput struct {
	Title           string   `json:"title"`
	Description     *string  `json:"description,omitempty"`
	StartTime       int      `json:"startTime"`
	EndTime         int      `json:"endTime"`
	ParticipantsIDs []string `json:"participantsIDs,omitempty"`
	Notes           *string  `json:"notes,omitempty"`
}

type Meeting struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	Description  *string   `json:"description,omitempty"`
	StartTime    int       `json:"startTime"`
	EndTime      int       `json:"endTime"`
	Participants []*User   `json:"participants,omitempty"`
	Notes        *string   `json:"notes,omitempty"`
	Reminder     *Reminder `json:"reminder,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Reminder struct {
	ID          string `json:"id"`
	MeetingID   string `json:"meetingID"`
	TriggerTime int    `json:"triggerTime"`
}

type UpdateMeetingInput struct {
	Title           *string  `json:"title,omitempty"`
	Description     *string  `json:"description,omitempty"`
	StartTime       *int     `json:"startTime,omitempty"`
	EndTime         *int     `json:"endTime,omitempty"`
	ParticipantsIDs []string `json:"participantsIDs,omitempty"`
	Notes           *string  `json:"notes,omitempty"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
