version: '3.9'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  db:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nycu
      - MONGO_INITDB_ROOT_PASSWORD=nycu
    volumes:
      - mongo-data:/data/db
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=nycu
      - ME_CONFIG_MONGODB_ADMINPASSWORD=nycu
      - ME_CONFIG_MONGODB_URL=mongodb://nycu:nycu@db:27017/
    depends_on:
      - db
  
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379
    restart: always

  meeting-center-api:
    image: meeting-center-api
    ports:
      - 8080:8080
    env_file:
      - ../.env
    depends_on:
      - db
      - jaeger
      - redis

volumes:
  mongo-data: